version: "3.8"
name: mysql
services:
  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - database_mysql

networks:
  database_mysql:
    name: database_mysql