version: "3.7"
name: postgres
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    networks:
      - database_postgres

networks:
    database_postgres:
        name: database_postgres
